<?php

namespace App\Services\RAG;

use App\Jobs\GenerateLawEmbeddingsJob;
use App\Models\LawArticle;
use App\Models\LawEmbedding;
use App\Models\LawFile;
use App\Models\LawRegistry;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class LawProcessingService
{
    public function __construct(
        protected LawParserService $parser,
        protected EmbeddingService $embeddingService
    ) {}

    /**
     * Process a law file: parse articles and generate embeddings
     */
    public function processLawFile(LawFile $lawFile): array
    {
        DB::beginTransaction();
        
        try {
            // Parse articles
            $articles = $this->parser->parseFile($lawFile);
            
            if (empty($articles)) {
                Log::warning("No articles found in {$lawFile->filename}");
                DB::rollBack();
                return ['success' => false, 'message' => 'No articles found'];
            }

            // Save articles to database
            $savedArticles = [];
            foreach ($articles as $articleData) {
                $article = LawArticle::create([
                    'law_registry_id' => $lawFile->law_registry_id,
                    'law_file_id' => $lawFile->id,
                    'article_number' => $articleData['article_number'],
                    'article_text' => $articleData['article_text'],
                    'start_line' => $articleData['start_line'],
                    'end_line' => $articleData['end_line'],
                    'keywords' => $this->parser->extractKeywords($articleData['article_text']),
                ]);
                
                $savedArticles[] = $article;
            }

            // Update file status
            $lawFile->update([
                'total_articles' => count($savedArticles),
                'is_processed' => true,
                'processed_at' => now(),
            ]);

            DB::commit();

            // Embeddings are generated by a separate queued job (GenerateLawEmbeddingsJob) to avoid timeout

            Log::info("Processed {$lawFile->filename}: {$lawFile->total_articles} articles");

            return [
                'success' => true,
                'articles_count' => count($savedArticles),
                'message' => "تم معالجة {$lawFile->filename} بنجاح: {$lawFile->total_articles} مادة",
            ];
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error("Failed to process {$lawFile->filename}", [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return [
                'success' => false,
                'message' => 'فشلت المعالجة: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * Generate embeddings for articles
     */
    public function generateEmbeddingsForArticles(array $articles): void
    {
        foreach ($articles as $article) {
            try {
                $this->generateEmbeddingForArticle($article);
            } catch (\Exception $e) {
                Log::error("Failed to generate embedding for article {$article->id}", [
                    'error' => $e->getMessage(),
                ]);
            }
        }
    }

    /**
     * Generate embedding for a single article
     */
    public function generateEmbeddingForArticle(LawArticle $article): ?LawEmbedding
    {
        // Check if embedding already exists
        if ($article->hasEmbedding()) {
            return $article->embedding;
        }

        // Prepare text for embedding (article + context)
        $textForEmbedding = $this->prepareTextForEmbedding($article);

        try {
            $embeddingData = $this->embeddingService->generateEmbedding($textForEmbedding);
            
            if (empty($embeddingData['embedding'])) {
                Log::warning("Empty embedding generated for article {$article->id}");
                return null;
            }

            $embedding = new LawEmbedding([
                'law_article_id' => $article->id,
                'embedding_model' => $embeddingData['model'],
                'embedding_dimensions' => count($embeddingData['embedding']),
            ]);

            $embedding->setVectorArray($embeddingData['embedding']);
            $embedding->save();

            Log::info("Generated embedding for article {$article->id}");

            return $embedding;
        } catch (\Exception $e) {
            Log::error("Embedding generation failed for article {$article->id}", [
                'error' => $e->getMessage(),
            ]);
            return null;
        }
    }

    /**
     * Generate embeddings for all articles of a law file (batch where possible). Never throws.
     */
    public function generateEmbeddingsForLawFile(LawFile $lawFile): array
    {
        $articles = $lawFile->articles()->with('lawRegistry')->get();
        if ($articles->isEmpty()) {
            return ['success' => true, 'processed' => 0];
        }

        $chunkSize = 50;
        $processed = 0;
        $texts = [];
        foreach ($articles as $article) {
            if ($article->hasEmbedding()) {
                continue;
            }
            $texts[$article->id] = $this->prepareTextForEmbedding($article);
        }
        $articlesById = $articles->keyBy('id');
        foreach (array_chunk($texts, $chunkSize, true) as $chunk) {
            $textValues = array_values($chunk);
            $articleIds = array_keys($chunk);
            try {
                $embeddings = $this->embeddingService->generateEmbeddingsBatch($textValues);
                if (count($embeddings) !== count($articleIds)) {
                    throw new \RuntimeException('Batch size mismatch');
                }
                foreach (array_combine($articleIds, $embeddings) as $articleId => $embeddingVector) {
                    $article = $articlesById->get($articleId);
                    if (!$article || !is_array($embeddingVector)) {
                        continue;
                    }
                    $embedding = new LawEmbedding([
                        'law_article_id' => $article->id,
                        'embedding_model' => 'openai/text-embedding-3-small',
                        'embedding_dimensions' => count($embeddingVector),
                    ]);
                    $embedding->setVectorArray($embeddingVector);
                    $embedding->save();
                    $processed++;
                }
            } catch (\Throwable $e) {
                Log::warning("Batch embedding failed, falling back to one-by-one", ['error' => $e->getMessage()]);
                foreach ($articleIds as $articleId) {
                    $article = $articlesById->get($articleId);
                    if ($article && !$article->hasEmbedding()) {
                        try {
                            $this->generateEmbeddingForArticle($article);
                            $processed++;
                        } catch (\Throwable $_) {
                            // already no-throw in generateEmbeddingForArticle
                        }
                    }
                }
            }
        }
        return ['success' => true, 'processed' => $processed];
    }

    /**
     * Prepare article text for embedding generation
     */
    protected function prepareTextForEmbedding(LawArticle $article): string
    {
        $lawName = $article->lawRegistry->name;
        $articleNumber = $article->article_number;
        $articleText = $article->article_text;

        // Format: "Law Name - Article Number: Article Text"
        return "{$lawName} - المادة {$articleNumber}: {$articleText}";
    }

    /**
     * Process all unprocessed files in a law registry
     */
    public function processLawRegistry(LawRegistry $lawRegistry): array
    {
        $unprocessedFiles = $lawRegistry->files()->where('is_processed', false)->get();
        
        if ($unprocessedFiles->isEmpty()) {
            return [
                'success' => true,
                'message' => 'جميع الملفات معالجة بالفعل',
                'processed_count' => 0,
            ];
        }

        $results = [];
        $successCount = 0;

        foreach ($unprocessedFiles as $file) {
            $result = $this->processLawFile($file);
            $results[] = $result;

            if ($result['success']) {
                $successCount++;
                GenerateLawEmbeddingsJob::dispatch($file);
            }
        }

        return [
            'success' => $successCount > 0,
            'processed_count' => $successCount,
            'total_files' => count($unprocessedFiles),
            'message' => "تمت معالجة {$successCount} من {$unprocessedFiles->count()} ملفات",
            'details' => $results,
        ];
    }

    /**
     * Reprocess all articles (regenerate embeddings)
     */
    public function reprocessAllArticles(): array
    {
        $articles = LawArticle::all();
        $processedCount = 0;

        foreach ($articles as $article) {
            // Delete existing embedding
            $article->embedding?->delete();
            
            try {
                $this->generateEmbeddingForArticle($article);
                $processedCount++;
            } catch (\Exception $e) {
                Log::error("Failed to reprocess article {$article->id}");
            }
        }

        return [
            'success' => true,
            'processed_count' => $processedCount,
            'total_articles' => $articles->count(),
        ];
    }
}
