<?php

namespace App\Services\RAG;

use App\Jobs\GenerateLawEmbeddingsJob;
use App\Models\LawArticle;
use App\Models\LawEmbedding;
use App\Models\LawFile;
use App\Models\LawRegistry;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class LawProcessingService
{
    public function __construct(
        protected LawParserService $parser,
        protected EmbeddingService $embeddingService
    ) {}

    /**
     * Map an Arabic status string from the law file header to the DB enum value.
     */
    protected function mapArabicStatus(string $arabicStatus): string
    {
        return match ($arabicStatus) {
            'ساري'  => 'active',
            'لاغي'  => 'abrogated',
            default => 'draft',
        };
    }

    /**
     * Process a law file: parse articles and generate embeddings
     */
    public function processLawFile(LawFile $lawFile): array
    {
        DB::beginTransaction();

        try {
            // Read raw file content for header parsing
            $filePath = Storage::disk('local')->path($lawFile->file_path);
            $content = file_exists($filePath) ? file_get_contents($filePath) : '';

            // Parse header metadata and update LawRegistry accordingly
            if (!empty($content)) {
                $headerData = $this->parser->parseHeader($content);

                $statusMapped = $this->mapArabicStatus($headerData['status']);

                $existingMeta = $lawFile->lawRegistry?->metadata ?? [];
                $newMeta = array_merge($existingMeta, array_filter([
                    'decree_ref' => $headerData['decree_ref'],
                    'summary'    => $headerData['summary'],
                ]));

                $lawFile->lawRegistry?->update([
                    'status'   => $statusMapped,
                    'metadata' => $newMeta,
                ]);
            }

            // Parse articles
            $articles = $this->parser->parseFile($lawFile);

            if (empty($articles)) {
                Log::warning("No articles found in {$lawFile->filename}");
                DB::rollBack();

                $errorMessage = 'لم يتم العثور على أي مواد قانونية في الملف. تأكد من أن الملف يحتوي على مواد بصيغة صحيحة (مثل: "المادة الأولى" أو "١/١" أو "مادة 1")';

                return [
                    'success' => false,
                    'message' => $errorMessage,
                ];
            }

            // Save articles to database
            $savedArticles = [];
            foreach ($articles as $articleData) {
                $article = LawArticle::create([
                    'law_registry_id' => $lawFile->law_registry_id,
                    'law_file_id' => $lawFile->id,
                    'article_number' => $articleData['article_number'],
                    'article_text' => $articleData['article_text'],
                    'start_line' => $articleData['start_line'],
                    'end_line' => $articleData['end_line'],
                    'keywords' => $this->parser->extractKeywords($articleData['article_text']),
                ]);

                $savedArticles[] = $article;
            }

            // Update file status
            $lawFile->update([
                'total_articles' => count($savedArticles),
                'is_processed' => true,
                'processed_at' => now(),
            ]);

            DB::commit();

            // Embeddings are generated by a separate queued job (GenerateLawEmbeddingsJob) to avoid timeout

            Log::info("Processed {$lawFile->filename}: {$lawFile->total_articles} articles");

            return [
                'success' => true,
                'articles_count' => count($savedArticles),
                'message' => "تم معالجة {$lawFile->filename} بنجاح: {$lawFile->total_articles} مادة",
            ];
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error("Failed to process {$lawFile->filename}", [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            $userFriendlyMessage = $this->getUserFriendlyErrorMessage($e);
            
            return [
                'success' => false,
                'message' => $userFriendlyMessage,
            ];
        }
    }

    /**
     * Generate embeddings for articles
     */
    public function generateEmbeddingsForArticles(array $articles): void
    {
        foreach ($articles as $article) {
            try {
                $this->generateEmbeddingForArticle($article);
            } catch (\Exception $e) {
                Log::error("Failed to generate embedding for article {$article->id}", [
                    'error' => $e->getMessage(),
                ]);
            }
        }
    }

    /**
     * Generate embedding for a single article
     */
    public function generateEmbeddingForArticle(LawArticle $article): ?LawEmbedding
    {
        // Check if embedding already exists
        if ($article->hasEmbedding()) {
            return $article->embedding;
        }

        // Prepare text for embedding (article + context)
        $textForEmbedding = $this->prepareTextForEmbedding($article);

        try {
            $embeddingData = $this->embeddingService->generateEmbedding($textForEmbedding);
            
            if (empty($embeddingData['embedding'])) {
                Log::warning("Empty embedding generated for article {$article->id}");
                return null;
            }

            $embedding = new LawEmbedding([
                'law_article_id' => $article->id,
                'embedding_model' => $embeddingData['model'],
                'embedding_dimensions' => count($embeddingData['embedding']),
            ]);

            $embedding->setVectorArray($embeddingData['embedding']);
            $embedding->save();

            Log::info("Generated embedding for article {$article->id}");

            return $embedding;
        } catch (\Exception $e) {
            Log::error("Embedding generation failed for article {$article->id}", [
                'error' => $e->getMessage(),
            ]);
            return null;
        }
    }

    /**
     * Generate embeddings for all articles of a law file (batch where possible). Never throws.
     */
    public function generateEmbeddingsForLawFile(LawFile $lawFile): array
    {
        $articles = $lawFile->articles()->with('lawRegistry')->get();
        if ($articles->isEmpty()) {
            return ['success' => true, 'processed' => 0];
        }

        $chunkSize = 50;
        $processed = 0;
        $texts = [];
        foreach ($articles as $article) {
            if ($article->hasEmbedding()) {
                continue;
            }
            $texts[$article->id] = $this->prepareTextForEmbedding($article);
        }
        $articlesById = $articles->keyBy('id');
        foreach (array_chunk($texts, $chunkSize, true) as $chunk) {
            $textValues = array_values($chunk);
            $articleIds = array_keys($chunk);
            try {
                $embeddings = $this->embeddingService->generateEmbeddingsBatch($textValues);
                if (count($embeddings) !== count($articleIds)) {
                    throw new \RuntimeException('Batch size mismatch');
                }
                foreach (array_combine($articleIds, $embeddings) as $articleId => $embeddingVector) {
                    $article = $articlesById->get($articleId);
                    if (!$article || !is_array($embeddingVector)) {
                        continue;
                    }
                    $embedding = new LawEmbedding([
                        'law_article_id' => $article->id,
                        'embedding_model' => 'openai/text-embedding-3-small',
                        'embedding_dimensions' => count($embeddingVector),
                    ]);
                    $embedding->setVectorArray($embeddingVector);
                    $embedding->save();
                    $processed++;
                }
            } catch (\Throwable $e) {
                Log::warning("Batch embedding failed, falling back to one-by-one", ['error' => $e->getMessage()]);
                foreach ($articleIds as $articleId) {
                    $article = $articlesById->get($articleId);
                    if ($article && !$article->hasEmbedding()) {
                        try {
                            $this->generateEmbeddingForArticle($article);
                            $processed++;
                        } catch (\Throwable $_) {
                            // already no-throw in generateEmbeddingForArticle
                        }
                    }
                }
            }
        }
        return ['success' => true, 'processed' => $processed];
    }

    /**
     * Prepare article text for embedding generation.
     * Strips noise markers and enforces a 24,000-character budget (~6,000 tokens).
     */
    protected function prepareTextForEmbedding(LawArticle $article): string
    {
        $lawName = $article->lawRegistry?->name ?? 'نظام غير معروف';
        $articleNumber = $article->article_number;
        $articleText = $article->article_text;

        // Strip "(معدّل)" amendment suffixes
        $articleText = preg_replace('/\s*\(معدّل\)/u', '', $articleText);

        // Strip remaining bracket markers like [نص المادة] or [معدل]
        $articleText = preg_replace('/\[[^\]]*\]/u', '', $articleText);

        $articleText = trim($articleText);

        $prepared = "{$lawName} - المادة {$articleNumber}: {$articleText}";

        // Character budget: ~6,000 tokens ≈ 24,000 characters
        $charBudget = 24000;
        if (mb_strlen($prepared) > $charBudget) {
            Log::warning('Article text exceeds embedding character budget; truncating', [
                'article_id' => $article->id,
                'law_name'   => $lawName,
                'original_length' => mb_strlen($prepared),
                'truncated_to'    => $charBudget,
            ]);
            $prepared = mb_substr($prepared, 0, $charBudget);
        }

        return $prepared;
    }

    /**
     * Process all unprocessed files in a law registry
     */
    public function processLawRegistry(LawRegistry $lawRegistry): array
    {
        $unprocessedFiles = $lawRegistry->files()->where('is_processed', false)->get();
        
        if ($unprocessedFiles->isEmpty()) {
            return [
                'success' => true,
                'message' => 'جميع الملفات معالجة بالفعل',
                'processed_count' => 0,
            ];
        }

        $results = [];
        $successCount = 0;

        foreach ($unprocessedFiles as $file) {
            $result = $this->processLawFile($file);
            $results[] = $result;

            if ($result['success']) {
                $successCount++;
                GenerateLawEmbeddingsJob::dispatch($file);
            }
        }

        return [
            'success' => $successCount > 0,
            'processed_count' => $successCount,
            'total_files' => count($unprocessedFiles),
            'message' => "تمت معالجة {$successCount} من {$unprocessedFiles->count()} ملفات",
            'details' => $results,
        ];
    }

    /**
     * Reprocess all articles (regenerate embeddings)
     */
    public function reprocessAllArticles(): array
    {
        $articles = LawArticle::all();
        $processedCount = 0;

        foreach ($articles as $article) {
            // Delete existing embedding
            $article->embedding?->delete();
            
            try {
                $this->generateEmbeddingForArticle($article);
                $processedCount++;
            } catch (\Exception $e) {
                Log::error("Failed to reprocess article {$article->id}");
            }
        }

        return [
            'success' => true,
            'processed_count' => $processedCount,
            'total_articles' => $articles->count(),
        ];
    }

    /**
     * Convert technical error messages to user-friendly Arabic messages
     */
    protected function getUserFriendlyErrorMessage(\Exception $e): string
    {
        $message = $e->getMessage();
        
        if (str_contains($message, 'Law file not found') || str_contains($message, 'file_exists')) {
            return 'لم يتم العثور على ملف النظام في التخزين. تأكد من رفع الملف بشكل صحيح.';
        }
        
        if (str_contains($message, 'No articles found')) {
            return 'لم يتم العثور على أي مواد قانونية في الملف. تأكد من أن الملف يحتوي على مواد بصيغة صحيحة (مثل: "المادة الأولى" أو "١/١" أو "مادة 1")';
        }
        
        if (str_contains($message, 'encoding') || str_contains($message, 'charset') || str_contains($message, 'iconv')) {
            return 'خطأ في ترميز الملف. تأكد من أن الملف بصيغة UTF-8 أو نص عربي صحيح.';
        }
        
        if (str_contains($message, 'timeout') || str_contains($message, 'time limit') || str_contains($message, 'Maximum execution')) {
            return 'انتهت مهلة معالجة الملف. الملف قد يكون كبيراً جداً. حاول تقسيمه إلى ملفات أصغر.';
        }
        
        if (str_contains($message, 'memory') || str_contains($message, 'Memory exhausted') || str_contains($message, 'Allowed memory')) {
            return 'نفدت ذاكرة الخادم أثناء معالجة الملف. الملف قد يكون كبيراً جداً. حاول تقسيمه إلى ملفات أصغر.';
        }
        
        if (str_contains($message, 'file_get_contents') || str_contains($message, 'fopen')) {
            return 'فشلت قراءة الملف. تأكد من صلاحيات الملف والمسار.';
        }
        
        if (str_contains($message, 'Connection') || str_contains($message, 'network')) {
            return 'خطأ في الاتصال بخدمة الذكاء الاصطناعي. تأكد من الاتصال بالإنترنت وصحة مفاتيح API.';
        }
        
        return 'فشلت المعالجة: ' . $message;
    }
}
